# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/henry/Documents/DONE/DONE-19-1-2018/DOING/RoadSignDetection

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/henry/Documents/DONE/DONE-19-1-2018/DOING/RoadSignDetection

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/henry/Documents/DONE/DONE-19-1-2018/DOING/RoadSignDetection/CMakeFiles /home/henry/Documents/DONE/DONE-19-1-2018/DOING/RoadSignDetection/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/henry/Documents/DONE/DONE-19-1-2018/DOING/RoadSignDetection/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named RoadSignRecognition

# Build rule for target.
RoadSignRecognition: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 RoadSignRecognition
.PHONY : RoadSignRecognition

# fast build rule for target.
RoadSignRecognition/fast:
	$(MAKE) -f CMakeFiles/RoadSignRecognition.dir/build.make CMakeFiles/RoadSignRecognition.dir/build
.PHONY : RoadSignRecognition/fast

define.o: define.cpp.o

.PHONY : define.o

# target to build an object file
define.cpp.o:
	$(MAKE) -f CMakeFiles/RoadSignRecognition.dir/build.make CMakeFiles/RoadSignRecognition.dir/define.cpp.o
.PHONY : define.cpp.o

define.i: define.cpp.i

.PHONY : define.i

# target to preprocess a source file
define.cpp.i:
	$(MAKE) -f CMakeFiles/RoadSignRecognition.dir/build.make CMakeFiles/RoadSignRecognition.dir/define.cpp.i
.PHONY : define.cpp.i

define.s: define.cpp.s

.PHONY : define.s

# target to generate assembly for a file
define.cpp.s:
	$(MAKE) -f CMakeFiles/RoadSignRecognition.dir/build.make CMakeFiles/RoadSignRecognition.dir/define.cpp.s
.PHONY : define.cpp.s

ihlsandnhs.o: ihlsandnhs.cpp.o

.PHONY : ihlsandnhs.o

# target to build an object file
ihlsandnhs.cpp.o:
	$(MAKE) -f CMakeFiles/RoadSignRecognition.dir/build.make CMakeFiles/RoadSignRecognition.dir/ihlsandnhs.cpp.o
.PHONY : ihlsandnhs.cpp.o

ihlsandnhs.i: ihlsandnhs.cpp.i

.PHONY : ihlsandnhs.i

# target to preprocess a source file
ihlsandnhs.cpp.i:
	$(MAKE) -f CMakeFiles/RoadSignRecognition.dir/build.make CMakeFiles/RoadSignRecognition.dir/ihlsandnhs.cpp.i
.PHONY : ihlsandnhs.cpp.i

ihlsandnhs.s: ihlsandnhs.cpp.s

.PHONY : ihlsandnhs.s

# target to generate assembly for a file
ihlsandnhs.cpp.s:
	$(MAKE) -f CMakeFiles/RoadSignRecognition.dir/build.make CMakeFiles/RoadSignRecognition.dir/ihlsandnhs.cpp.s
.PHONY : ihlsandnhs.cpp.s

image_utils.o: image_utils.cpp.o

.PHONY : image_utils.o

# target to build an object file
image_utils.cpp.o:
	$(MAKE) -f CMakeFiles/RoadSignRecognition.dir/build.make CMakeFiles/RoadSignRecognition.dir/image_utils.cpp.o
.PHONY : image_utils.cpp.o

image_utils.i: image_utils.cpp.i

.PHONY : image_utils.i

# target to preprocess a source file
image_utils.cpp.i:
	$(MAKE) -f CMakeFiles/RoadSignRecognition.dir/build.make CMakeFiles/RoadSignRecognition.dir/image_utils.cpp.i
.PHONY : image_utils.cpp.i

image_utils.s: image_utils.cpp.s

.PHONY : image_utils.s

# target to generate assembly for a file
image_utils.cpp.s:
	$(MAKE) -f CMakeFiles/RoadSignRecognition.dir/build.make CMakeFiles/RoadSignRecognition.dir/image_utils.cpp.s
.PHONY : image_utils.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/RoadSignRecognition.dir/build.make CMakeFiles/RoadSignRecognition.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/RoadSignRecognition.dir/build.make CMakeFiles/RoadSignRecognition.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/RoadSignRecognition.dir/build.make CMakeFiles/RoadSignRecognition.dir/main.cpp.s
.PHONY : main.cpp.s

math_utils.o: math_utils.cpp.o

.PHONY : math_utils.o

# target to build an object file
math_utils.cpp.o:
	$(MAKE) -f CMakeFiles/RoadSignRecognition.dir/build.make CMakeFiles/RoadSignRecognition.dir/math_utils.cpp.o
.PHONY : math_utils.cpp.o

math_utils.i: math_utils.cpp.i

.PHONY : math_utils.i

# target to preprocess a source file
math_utils.cpp.i:
	$(MAKE) -f CMakeFiles/RoadSignRecognition.dir/build.make CMakeFiles/RoadSignRecognition.dir/math_utils.cpp.i
.PHONY : math_utils.cpp.i

math_utils.s: math_utils.cpp.s

.PHONY : math_utils.s

# target to generate assembly for a file
math_utils.cpp.s:
	$(MAKE) -f CMakeFiles/RoadSignRecognition.dir/build.make CMakeFiles/RoadSignRecognition.dir/math_utils.cpp.s
.PHONY : math_utils.cpp.s

post-processing.o: post-processing.cpp.o

.PHONY : post-processing.o

# target to build an object file
post-processing.cpp.o:
	$(MAKE) -f CMakeFiles/RoadSignRecognition.dir/build.make CMakeFiles/RoadSignRecognition.dir/post-processing.cpp.o
.PHONY : post-processing.cpp.o

post-processing.i: post-processing.cpp.i

.PHONY : post-processing.i

# target to preprocess a source file
post-processing.cpp.i:
	$(MAKE) -f CMakeFiles/RoadSignRecognition.dir/build.make CMakeFiles/RoadSignRecognition.dir/post-processing.cpp.i
.PHONY : post-processing.cpp.i

post-processing.s: post-processing.cpp.s

.PHONY : post-processing.s

# target to generate assembly for a file
post-processing.cpp.s:
	$(MAKE) -f CMakeFiles/RoadSignRecognition.dir/build.make CMakeFiles/RoadSignRecognition.dir/post-processing.cpp.s
.PHONY : post-processing.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... RoadSignRecognition"
	@echo "... define.o"
	@echo "... define.i"
	@echo "... define.s"
	@echo "... ihlsandnhs.o"
	@echo "... ihlsandnhs.i"
	@echo "... ihlsandnhs.s"
	@echo "... image_utils.o"
	@echo "... image_utils.i"
	@echo "... image_utils.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... math_utils.o"
	@echo "... math_utils.i"
	@echo "... math_utils.s"
	@echo "... post-processing.o"
	@echo "... post-processing.i"
	@echo "... post-processing.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

